trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  provisionScriptPath: 'scripts/provision.sh'
  deploymentScriptPath: 'scripts/deployment.sh'
  azSubscription: 'infradeploy'

steps:
  - task: AzureCLI@2
    displayName: 'Updating infrastructure'
    inputs:
      azureSubscription: $(azSubscription)
      scriptType: 'bash'
      scriptLocation: 'scriptPath'
      scriptPath: $(provisionScriptPath)

  - task: Npm@1
    displayName: 'Install dependencies for toxic API'
    inputs:
      command: 'install'
      workingDir: $(System.DefaultWorkingDirectory)/api/

  - task: Npm@1
    displayName: 'Transpile toxic API'
    inputs:
      command: 'custom'
      workingDir: $(System.DefaultWorkingDirectory)/api/
      customCommand: 'run build:production'

  - task: ArchiveFiles@2
    displayName: 'Archive toxic API'
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)/api/
      includeRootFolder: true
      archiveType: zip
      archiveFile: toxicapi.zip
      replaceExistingArchive: true

  - task: AzureFunctionApp@1
    displayName: 'Deploy toxic API'
    inputs:
      azureSubscription: $(azSubscription)
      appName: 'toxicitycheck'
      appType: 'functionAppLinux'
      slotName: 'production'
      deploymentMethod: 'runFromPackage'
      package: $(System.DefaultWorkingDirectory)/**/*.zip
